---
- name: set user fact
  set_fact:
    bootstrap_user_fact: "{{ item }}"

- name: add user
  user:
    name: "{{ bootstrap_user_fact['name'] }}"
    groups: "{{ bootstrap_user_fact['groups'] | default(omit)}}"
    home: "{{  bootstrap_user_fact['home'] | default('/home/' + bootstrap_user_fact['name']) }}"
    state: "{{ bootstrap_user_fact['state'] | default('present') }}"

- name: Set authorized keys for user
  authorized_key:
    user: "{{ bootstrap_user_fact['name'] }}"
    key: '{{ item }}'
    state: present
    exclusive: True
  with_items: "{{ bootstrap_user_fact['keys'] }}"

- name: Create sudoers
  template:
    src: sudoers.d.jinja2
    dest: "{{ '/etc/sudoers.d/' + bootstrap_user_fact['name'] }}"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
  when: not (bootstrap_user_fact['password_sudo'] | default(true)) | bool

- name: Remove sudoers
  file:
    path: "{{ '/etc/sudoers.d/' + bootstrap_user_fact['name'] }}"
    state: absent
  when: (bootstrap_user_fact['password_sudo'] | default(true)) | bool
